stages:
  - build
  - test

variables:
  INSTALL_DIR: PALISADE_local_install

# Build jobs

build_wasm:
  stage: build
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev") || $DO_CI
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  before_script:
    - pwd
    - source /home/ubuntu/emsdk/emsdk_env.sh
    - git clone -b master https://gitlab.com/palisade/palisade-development.git PALISADE
    - cd PALISADE
    - mkdir -p build
    - cd build
    - mkdir -p ../../$INSTALL_DIR
    - emcmake cmake -DCMAKE_INSTALL_PREFIX=../../$INSTALL_DIR -DBUILD_UNITTESTS=ON -DBUILD_BENCHMARKS=OFF -DBUILD_EXTRAS=OFF -DBUILD_EXAMPLES=OFF ..
    - emmake make install -j6
    - cat ../../$INSTALL_DIR/lib/Palisade/PalisadeConfig.cmake
    - ls ../../$INSTALL_DIR/lib
    - ls ../../$INSTALL_DIR/lib/Palisade
    - cd ../..
    # - rm -rf PALISADE
  script:
    - pwd
    - ls
    - ls $INSTALL_DIR/lib
    - ls $INSTALL_DIR/lib/Palisade
    - export LD_LIBRARY_PATH=$(pwd)/build/lib:$(pwd)/${INSTALL_DIR}/lib
    - echo $LD_LIBRARY_PATH
    - mkdir -p build
    - cd build
    - emcmake cmake -DBUILD_UNITTESTS=ON .. -DCMAKE_PREFIX_PATH=$(realpath ../${INSTALL_DIR}/lib) -DPalisade_DIR=$(realpath ../${INSTALL_DIR}/lib/Palisade)
    - emmake make -j6
    - ls
    - pwd
    - cd ..
    - pwd
  artifacts:
    expire_in: 1 day
    paths:
      - lib
      - unittest
      - $INSTALL_DIR
      - PALISADE/build

# Test jobs

test_wasm:
  rules:
    - if: $BIN_CI
      when: never
    - if: ($CI_COMMIT_BRANCH == "master") || $DO_CI
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  stage: test
  before_script:
    - export LD_LIBRARY_PATH=$(pwd)/build/lib:$(pwd)/${INSTALL_DIR}/lib
  script:
    # - nodejs PALISADE/build/unittest/binfhe_tests.js
    - nodejs PALISADE/build/unittest/pke_tests.js
    - nodejs PALISADE/build//unittest/core_tests.js
  artifacts:
    paths:
      - test_detail.xml
    expire_in: 1 hours
  dependencies:
    - build_wasm

